apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ollama
    {{- include "stock-analyst-ml.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: ollama
  ports:
    - name: http
      port: {{ .Values.ollama.port }}
      targetPort: http
