apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    {{- include "stock-analyst-obs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: {{ .Values.loki.port }}
      targetPort: http
