apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qdrant
    {{- include "stock-analyst-data.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.qdrant.storage }}
