apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api
    {{- include "stock-analyst-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
