apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak
    {{- include "stock-analyst-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        {{- include "stock-analyst-app.labels" . | nindent 8 }}
    spec:
      {{- include "stock-analyst-app.nodeAffinity" . | nindent 6 }}
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          command: {{ .Values.keycloak.command | toJson }}
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Values.dependencies.postgres.host }}:{{ .Values.dependencies.postgres.port }}/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret }}
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret }}
                  key: POSTGRES_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret }}
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret }}
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.port }}
          resources:
            requests:
              cpu: {{ .Values.keycloak.resources.requests.cpu }}
              memory: {{ .Values.keycloak.resources.requests.memory }}
            limits:
              cpu: {{ .Values.keycloak.resources.limits.cpu }}
              memory: {{ .Values.keycloak.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
