apiVersion: v1
kind: Namespace
metadata:
  name: stock-analyst-ml
  labels:
    app: stock-analyst
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stock-analyst-ml-quota
  namespace: stock-analyst-ml
spec:
  hard:
    requests.cpu: "24"
    requests.memory: 80Gi
    limits.cpu: "24"
    limits.memory: 80Gi
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
