apiVersion: v1
kind: Namespace
metadata:
  name: stock-analyst-data
  labels:
    app: stock-analyst
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stock-analyst-data-quota
  namespace: stock-analyst-data
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 200Gi
    limits.cpu: "32"
    limits.memory: 200Gi
