apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    {{- include "stock-analyst-obs.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:{{ .Values.prometheus.port }}
        uid: prometheus
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:{{ .Values.loki.port }}
        uid: loki
