apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    {{- include "stock-analyst-obs.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage }}
